[package]
name = "resolvematrix-cli"
version.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "resolvematrix"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.4", features = ["derive"] }
resolvematrix = { workspace = true, features = ["aws_lc_rs"] }
tokio = { version = "1.53.1", features = ["rt"] }
tracing-subscriber = "0.3.23"
reqwest = { version = "0.13.2", default-features = false, features = ["rustls"] }
ruma = { version = "0.16.0", features = ["federation-api"] }
serde = { version = "1.0.229", features = ["derive"] }
